### ISSUE TITLE
App识别：『南北』微信_零钱提现

### ISSUE THREAD

**Issue by Oniokey** [dreamncn/Qianji_auto#100]
{"data":[{"des":"","identify":"app","fromApp":"com.tencent.mm","name":"『南北』微信零钱_提现至卡","tableList":{"shopRemark":"提现","money":"$1","fee":"","account2":"储蓄卡（$2）","account1":"零钱","shopName":"微信财付通","time":"$3","type":"2"},"text":"cache_user:服务费,cache_user2:中国银行微银行,cache_paytools:中国银行储蓄卡(2218),isSend:0,title:卡片消息,content:msg:appmsg:extinfo:,lowurl:,sourcedisplayname:,showtype:1,title:零钱提现到账,type:5,appattach:totallen:0,cdnthumburl:,aeskey:,attachid:,fileext:,cdnthumbaeskey:,content: t,content:,url:https://wx.tenpay.com/cgi-bin/mmpayweb-bin/jumpuserroll?trans_id=207211219100067111001661750800&accid=085e9858efad45aeb51400fc1,soundtype:0,mmreader:template_detail:template_show_type:1,text_content:cover:,color:,text:,new_tmpl_type:0,line_content:topline:value:color:#000000,word:￥0.90,key:color:#888888,word:提现金额,lines:line:[value:color:#000000,word:中国银行(2218),key:color:#888888,word:提现银行,value:color:#000000,word:2021-12-19 01:31:13,key:color:#888888,word:提现时间,value:color:#000000,word:2021-12-19 01:31:14,key:color:#888888,word:到账时间,value:color:#000000,word:你的零钱提现已到账至银行卡,key:color:#888888,word:备注],opitems:opitem:color:#000000,icon:,general_string:,weapp_path:,display_line_number:0,url:https://wx.tenpay.com/cgi-bin/mmpayweb-bin/jumpuserroll?trans_id=207211219100067111001661750800&accid=085e9858efad45aeb51400fc1,weapp_version:0,ext_id:,is_show_red_dot:0,hint_word:,weapp_username:,op_type:0,is_rich_text:0,word:查看详情,business_id:,weapp_state:0,show_type:0,publisher:nickname:微信支付,content: tt,username:wxzhifu,template_header:first_color:,title_color:,pub_time:1639848679,first_data:,title:零钱提现到账,category:item:is_pay_subscribe:0,video_height:0,sources:source:name:微信支付,content: t,content: t,appmsg_like_type:0,video_width:0,recommendation:,title:零钱提现到账,native_url:,content: t,cover:,weapp_version:0,vid:,pic_num:0,digest:n提现金额：￥0.90n提现银行：中国银行(2218)n提现时间：2021-12-19 01:31:13n到账时间：2021-12-19 01:31:14n你的零钱提现已到账至银行卡,cover_235_1:,weapp_username:,fileid:0,player:,cover_1_1:,del_flag:0,play_url:,shorturl:,pub_time:1639848679,pic_urls:,cover_16_9:,general_string:,template_op_type:0,weapp_path:,url:https://wx.tenpay.com/cgi-bin/mmpayweb-bin/jumpuserroll?trans_id=207211219100067111001661750800&accid=085e9858efad45aeb51400fc1,tweetid:,finder_feed:,play_length:0,comment_topic_id:0,music_source:0,longurl:,styles:topColor:#4ABB44,style:[color:#000000,range:6,5,font:s,color:#000000,range:17,10,font:s,color:#000000,range:33,19,font:s,color:#000000,range:58,19,font:s,color:#000000,range:78,13,font:s],itemshowtype:4,contentattr:0,weapp_state:0,show_complaint_button:0,count:1,name:微信支付,topnew:cover:,width:0,digest:n提现金额：￥0.90n提现银行：中国银行(2218)n提现时间：2021-12-19 01:31:13n到账时间：2021-12-19 01:31:14n你的零钱提现已到账至银行卡,content: ttt,height:0,type:0,content: tt,content: t,forbid_forward:0,notify_msg:,des:n提现金额：￥0.90n提现银行：中国银行(2218)n提现时间：2021-12-19 01:31:13n到账时间：2021-12-19 01:31:14n你的零钱提现已到账至银行卡,appid:,sourceusername:,sdkver:0,action:,template_id:VRpHf8aBQsCp6t1unh2IyO7pG9EQPzpQfeLLDY0kbV0,thumburl:,contentattr:0,fromusername:gh_3dfda90e39d6,appinfo:appname:微信支付,version:0,isforceupdate:1,status:3,cache_money:￥0.10","regular":"word:￥(\\d+\\.\\d+),key:color:#\\d\\d\\d\\d\\d\\d,word:[\\u4e00-\\u9fa5]+,lines:line:\\[value:color:#\\d\\d\\d\\d\\d\\d,word:[\\u4e00-\\u9fa5]+\\((\\d\\d\\d\\d)\\).*,pub_time:(.*),pic_urls"}],"from":"app"}

**Comment by dreamncn** [comment]
规则提交，请到此处：https://github.com/dreamncn/AutoResource
