### ISSUE TITLE
无法选择分类

### ISSUE THREAD

**Issue by TTsdzb** [dreamncn/Qianji_auto#101]
3.0.0 beta6
在如图界面无法选择分类，长按或点击都不行
也没有任何关于如何选择的提示
![Screenshot_2021-12-21-17-50-24-489_com miui home](https://user-images.githubusercontent.com/62687036/146909472-539dfca8-471d-49b1-99c1-09830dfb23fb.jpg)
若点击上方空白区域返回上个界面，其分类不会有任何变化

例如，我想选择分类“三餐”，点击“三餐”后它会变蓝，但并没有确定。长按也不能确定。

**Comment by TTsdzb** [comment]
如果我操作有误，能否告知？能否考虑添加类似2.x界面的操作提示？感谢

**Comment by dreamncn** [comment]
确定按钮在底下，已修。
