### ISSUE TITLE
js编辑无法选中删除

### ISSUE THREAD

**Issue by TTsdzb** [dreamncn/Qianji_auto#106]
在编辑自动分类时，长按并选中一段代码，再按退格键，没法删除选中的代码，只会删除选中的最后一个字符。正则表达式编辑器没试，不知道有没有一样的问题。

**Comment by TTsdzb** [comment]
同时会带来一个致命的问题：我要新建分类规则，进去以后是太公摘花写好的规则（上次编辑）。然后我没法全选删除，得手动把那一大堆代码从尾删到头，然后才能写我自己的代码；而且编辑器一次貌似只加载一部分，全选也只选中这一部分

**Comment by TTsdzb** [comment]
上个评论的问题实际上是由另一个bug引发的，详见下一个issue

**Comment by dreamncn** [comment]
> 在编辑自动分类时，长按并选中一段代码，再按退格键，没法删除选中的代码，只会删除选中的最后一个字符。正则表达式编辑器没试，不知道有没有一样的问题。

属于已知问题了，但是一直没有去解决，近期我看下吧

**Comment by TTsdzb** [comment]
> > 在编辑自动分类时，长按并选中一段代码，再按退格键，没法删除选中的代码，只会删除选中的最后一个字符。正则表达式编辑器没试，不知道有没有一样的问题。
> 
> 属于已知问题了，但是一直没有去解决，近期我看下吧

好的
