### ISSUE TITLE
无法新增分类规则

### ISSUE THREAD

**Issue by TTsdzb** [dreamncn/Qianji_auto#107]
先编辑自带的万能规则，再新建一个JS编辑的分类规则。此时会进入刚才万能规则的编辑页，而不是新的分类规则。编辑完成后点保存也是修改了自带的万能规则，并没有新建。

**Comment by dreamncn** [comment]
> 先编辑自带的万能规则，再新建一个JS编辑的分类规则。此时会进入刚才万能规则的编辑页，而不是新的分类规则。编辑完成后点保存也是修改了自带的万能规则，并没有新建。

这个是缓存导致的，后面优化。
