### ISSUE TITLE
息屏状态下收到支出收入短信或者微信红包就会崩溃

### ISSUE THREAD

**Issue by DAwn470520** [dreamncn/Qianji_auto#113]
息屏状态下收到支出收入短信或者微信红包就会崩溃
verCode:涅槃 3.2.5

error:
cn.dreamn.qianji_auto: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

stackTrace:
1.android.app.PendingIntent.checkFlags(PendingIntent.java:378)
2.android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:648)
3.android.app.PendingIntent.getBroadcast(PendingIntent.java:635)
4.cn.dreamn.qianji_auto.utils.runUtils.Tool.notice(Tool.java:89)
5.cn.dreamn.qianji_auto.bills.SendDataToApp$4.handleMessage(SendDataToApp.java:254)
6.android.os.Handler.dispatchMessage(Handler.java:106)
7.android.os.Looper.loopOnce(Looper.java:233)
8.android.os.Looper.loop(Looper.java:344)
9.android.app.ActivityThread.main(ActivityThread.java:8186)
10.java.lang.reflect.Method.invoke(Native Method)
11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by dreamncn** [comment]
已知bug，安卓12特产。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月5日(周六) 中午12:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dreamncn/Qianji_auto] 息屏状态下收到支出收入短信或者微信红包就会崩溃 (Issue #113)




 
息屏状态下收到支出收入短信或者微信红包就会崩溃
 verCode:涅槃 3.2.5
 
error:
 cn.dreamn.qianji_auto: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
 Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
 
stackTrace:
 1.android.app.PendingIntent.checkFlags(PendingIntent.java:378)
 2.android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:648)
 3.android.app.PendingIntent.getBroadcast(PendingIntent.java:635)
 4.cn.dreamn.qianji_auto.utils.runUtils.Tool.notice(Tool.java:89)
 5.cn.dreamn.qianji_auto.bills.SendDataToApp$4.handleMessage(SendDataToApp.java:254)
 6.android.os.Handler.dispatchMessage(Handler.java:106)
 7.android.os.Looper.loopOnce(Looper.java:233)
 8.android.os.Looper.loop(Looper.java:344)
 9.android.app.ActivityThread.main(ActivityThread.java:8186)
 10.java.lang.reflect.Method.invoke(Native Method)
 11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
 12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
