### ISSUE TITLE
如何添加账单分期

### ISSUE THREAD

**Issue by zhjcreator** [dreamncn/Qianji_auto#114]
钱迹有分期管理功能，请问下自动记账怎么自动添加分期账单？如京东白条分期，花呗分期等
![Screenshot_2022-02-13-20-43-09-68_405141075775372](https://user-images.githubusercontent.com/55911606/153753823-7098d9f2-25eb-4b90-8543-9d2d10bd5bd7.jpg)
另外微信京东白条公众号含有账单分期信息，但不含有商品详情；京东JD.COM公众号含有商品详情却不含有分期信息，不过都有订单号，请问如何整合这两者？

**Comment by dreamncn** [comment]
钱迹未提供分期的接口，暂不支持，只能手动添加。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月13日(周日) 晚上8:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dreamncn/Qianji_auto] 如何添加账单分期 (Issue #114)




 
钱迹有分期管理功能，请问下自动记账怎么自动添加分期账单？如京东白条分期，花呗分期等
 
 另外微信京东白条公众号含有账单分期信息，但不含有商品详情；京东JD.COM公众号含有商品详情却不含有分期信息，不过都有订单号，请问如何整合这两者？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhjcreator** [comment]
> 钱迹未提供分期的接口，暂不支持，只能手动添加。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年2月13日(周日) 晚上8:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [dreamncn/Qianji_auto] 如何添加账单分期 (Issue #114) 钱迹有分期管理功能，请问下自动记账怎么自动添加分期账单？如京东白条分期，花呗分期等 另外微信京东白条公众号含有账单分期信息，但不含有商品详情；京东JD.COM公众号含有商品详情却不含有分期信息，不过都有订单号，请问如何整合这两者？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好的，谢谢啦
