### ISSUE TITLE
过千金额识别问题

### ISSUE THREAD

**Issue by sjzybl** [dreamncn/Qianji_auto#118]
### 问题

有一些过千金额的表现形式为x,xxx（如1234元为1,234元，例如在中国银行的公众号中）。云端的规则被导入后并不能很好的识别这部分数字，导致整条信息无法识别。因为不知道规则的书写规范，所以不知道是软件在识别时没有考虑到这类数字还是规则的书写者没有考虑到这部分情况，故在此提交。望解决，祝好。

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by sjzybl** [comment]
还有一个问题，自动记账的UI在miui12.5系统中，如果是用大号字体，自动记账的UI前三栏就会不显示，只显示其他那一栏。

**Comment by dreamncn** [comment]
后者是bug，已知。
前者1,234这种自动记账会自动处理才对？方便提供数据吗？

**Comment by sjzybl** [comment]
我刚才重新试了试，现在可以了。以前我是通过把规则中这个地方改成 .*,.* 解决的，但是刚才再测试的时候就能识别了。

> 后者是bug，已知。 前者1,234这种自动记账会自动处理才对？方便提供数据吗？
