### ISSUE TITLE
微信红包还未收取就开始发起记账了

### ISSUE THREAD

**Issue by yadanchina** [dreamncn/Qianji_auto#119]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

微信红包还未收取就开始发起记账了

### 重现步骤

```bash
微信红包还未收取就开始发起记账了
```

### 相关环境说明

自动记账3.2.5
lsp1.8.1
安卓3.2.1.2

### 日志内容

微信红包还未收取就开始发起记账了

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该错误尚未被报告。

**Comment by dreamncn** [comment]
无效反馈。
