### ISSUE TITLE
BUG提示反馈

### ISSUE THREAD

**Issue by WY823002572** [dreamncn/Qianji_auto#127]
verCode:涅槃 3.2.8-011

error:
cn.dreamn.qianji_auto: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

stackTrace:
1.android.app.PendingIntent.checkFlags(PendingIntent.java:375)
2.android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
3.android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
4.cn.dreamn.qianji_auto.utils.runUtils.Tool.notice(Tool.java:89)
5.cn.dreamn.qianji_auto.bills.SendDataToApp$4.handleMessage(SendDataToApp.java:254)
6.android.os.Handler.dispatchMessage(Handler.java:106)
7.android.os.Looper.loopOnce(Looper.java:211)
8.android.os.Looper.loop(Looper.java:300)
9.android.app.ActivityThread.main(ActivityThread.java:8243)
10.java.lang.reflect.Method.invoke(Native Method)
11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by dreamncn** [comment]
已知问题，已修。
