### ISSUE TITLE
自动记账无法选择分类

### ISSUE THREAD

**Issue by Matthew-Harris-36** [dreamncn/Qianji_auto#136]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

付款后弹出自动记账的弹窗，点击分类无反应

### 重现步骤

```bash
1.付款，常用支付宝
2.弹出自动记账的弹窗
3.点击分类无反应，我是关闭懒人模式的。
```

### 相关环境说明

自动记账：3.3.1
LSP：1.8.3
钱迹：3.2.1.5b6

### 日志内容

[temp.log](https://github.com/dreamncn/Qianji_auto/files/9078321/temp.log)
自动记账备份：因为github不支持.backup格式文件上传，我就改了下后缀。
[Qianji_Auto_20220710103654.auto.backup.log](https://github.com/dreamncn/Qianji_auto/files/9078324/Qianji_Auto_20220710103654.auto.backup.log)

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该错误尚未被报告。

**Comment by dreamncn** [comment]
那是因为压根没有分类。
建议看下教程再操作。
