### ISSUE TITLE
短信识别会重复识别

### ISSUE THREAD

**Issue by NewHanly** [dreamncn/Qianji_auto#137]
### 问题

短信识别会重复两条，在记录里面任何信息都有两条重复记录，目前使用的LSPosed框架

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
仔细阅读文档

**Comment by SyntaxaR** [comment]
哥们找到原因了吗，手册翻了好几遍了都没找到原因，我是真纳闷QAQ

**Comment by SyntaxaR** [comment]
在酷安评论区解决了，xposed模式要关闭短信权限，不然会被框架推一次自己用权限读一次…然而文档里写的Xposed也需要短信权限就有点迷惑性

**Comment by dreamncn** [comment]
文档没写明白吗？
![Screenshot_2022-10-07-17-20-27-077_com android chrome](https://user-images.githubusercontent.com/37787014/194520095-8b325ce7-61e8-451f-a08f-0baf676a9540.jpg)
https://auto.ankio.net/pages/cc8aae/

**Comment by dreamncn** [comment]
> 在酷安评论区解决了，xposed模式要关闭短信权限，不然会被框架推一次自己用权限读一次…然而文档里写的Xposed也需要短信权限就有点迷惑性

如果文档的描述或者排版对使用造成了误解，欢迎进行pr
