### ISSUE TITLE
获取账户失败

### ISSUE THREAD

**Issue by KJ271058** [dreamncn/Qianji_auto#143]
verCode:涅槃 3.3.2

error:
BroadcastReceiver components are not allowed to register to receive intents

stackTrace:
1.android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:150)
2.android.app.ReceiverRestrictedContext.registerReceiver(ContextImpl.java:139)
3.android.content.ContextWrapper.registerReceiver(ContextWrapper.java:726)
4.android.widget.AbsListView.onAttachedToWindow(AbsListView.java:3240)
5.android.view.View.dispatchAttachedToWindow(View.java:20965)
6.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3571)
7.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
8.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
9.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
10.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
11.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
12.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
13.android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3578)
14.android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2845)
15.android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2297)
16.android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9197)
17.android.view.Choreographer$CallbackRecord.run(Choreographer.java:1186)
18.android.view.Choreographer.doCallbacks(Choreographer.java:986)
19.android.view.Choreographer.doFrame(Choreographer.java:912)
20.android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1171)
21.android.os.Handler.handleCallback(Handler.java:938)
22.android.os.Handler.dispatchMessage(Handler.java:99)
23.android.os.Looper.loopOnce(Looper.java:233)
24.android.os.Looper.loop(Looper.java:334)
25.android.app.ActivityThread.main(ActivityThread.java:8344)
26.java.lang.reflect.Method.invoke(Native Method)
27.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
28.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

**Comment by dreamncn** [comment]
检查自启动权限
