### ISSUE TITLE
这软件会出现在安装器的选择列表内

### ISSUE THREAD

**Issue by Zori9527** [dreamncn/Qianji_auto#151]
### 问题

![Screenshot_20221104-195902_Android System](https://user-images.githubusercontent.com/90077841/199969216-6b0c3740-bda2-4e36-b574-9fea2c868d01.jpg)
如图，明明没有安装器的功能，但是却会出现在安装器的选择列表内，并且没有找到去除的相关设置

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
已知
