### ISSUE TITLE
未适配微信8.0.33版本

### ISSUE THREAD

**Issue by chan1108** [dreamncn/Qianji_auto#164]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

新版微信无法使用

### 重现步骤

```bash
打开微信无法记账查看日志发现提示未适配
```

### 相关环境说明

自动记账版本3.3.2
lsp版本1.8.2
微信版本8.0.33

### 日志内容

[2023-03-09 11:16:31][Xposed日志-Ankio-微信]当前版本微信尚未适配！微信版本：8.0.33
[2023-03-09 11:16:31][Xposed日志-Ankio-微信]正在请求微信适配数据~

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该错误尚未被报告。

**Comment by dreamncn** [comment]
不影响

**Comment by chan1108** [comment]
> 不影响

但是微信升级之后再使用微信付款就没有弹出过自动记账的对话了

**Comment by charmingYouYou** [comment]
> 不影响

好像8.0.33确实有问题，看日志收不到广播事件，我降级的8.0.32就正常了

**Comment by 99665** [comment]
不光8.0.33用不了，8.0.34也用不了

**Comment by charmingYouYou** [comment]
> 不光8.0.33用不了，8.0.34也用不了

我降级到8.0.32之后又升级上去就好了...神奇, 现在是8.0.34

**Comment by dreamncn** [comment]
很显然，用不了不是自动记账的问题。
我在用的版本是8034，配合微x模块可以正常记账。

**Comment by dreamncn** [comment]
该issue关闭，不再进行讨论。
我个人是自动记账强依赖，如果新版本用不了。我会第一时间更新。
