### ISSUE TITLE
无障碍模式下获取不到短信内容

### ISSUE THREAD

**Issue by hhd165363088** [dreamncn/Qianji_auto#170]
### 问题

自动记账版本 涅槃 3.3.3 钱迹版本 3.2.1.11
手机是一加七pro 氢os10 之前一切正常 从昨更新了3.3.3在无障碍模式下就不能获取短信内容了 短信权限也给了 所有设置都正确 不知道是什么原因导致的 希望能得到解决

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by FroyoRab** [comment]
小米13 MIUI 14.0.31 重现问题，
自动记账版本 涅槃 3.3.4，钱迹版本 3.2.1.13-763
无障碍模式下，权限全给，短信获取不到。
包括部分应用也有获取问题，如京东，需要通过微信等触发一次后，再去京东才能获取。
