### ISSUE TITLE
无法激活模块

### ISSUE THREAD

**Issue by xmxu2022** [dreamncn/Qianji_auto#171]
### 问题

COLOROS 13

在启动时已允许读取储存，但是一直显示X，无法激活模块，请问是什么原因

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
请使用bug反馈模板进行反馈，没有信息，我也不知道为什么。
