### ISSUE TITLE
希望可以加回原3.3.2版本的通知栏记账提醒

### ISSUE THREAD

**Issue by HBH2023** [dreamncn/Qianji_auto#174]
### 描述建议

3.3.2版本会在手机没有解锁情况下有记账需要时，当重新解锁后会在通知栏提醒有几笔记账未处理，可以点击进行记账。这样可以防止有漏记账的。

### 该功能带来的好处或者优点

```bash
3.3.2版本会在手机没有解锁情况下有记账需要时，当重新解锁后会在通知栏提醒有几笔记账未处理，可以点击进行记账。这样可以防止有漏记账的。
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该功能尚未被报告。

**Comment by dreamncn** [comment]
这个功能没有被删除。
