### ISSUE TITLE
支付宝使用银行卡付钱时会记录两次

### ISSUE THREAD

**Issue by DioBoLuo** [dreamncn/Qianji_auto#184]
### 问题

支付宝使用银行卡付钱，银行卡会发短信，然后软件就会记录一次支付宝的一次银行卡的，有什么办法吗请问

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
没有
