### ISSUE TITLE
多次支付宝支出记账失败

### ISSUE THREAD

**Issue by reov** [dreamncn/Qianji_auto#185]
### 当前使用的框架

- [X] Lsposed
- [ ] EdXposed
- [ ] 太极（无极）
- [ ] 轮回
- [ ] 梦境
- [ ] 其他虚拟框架

### 描述错误

记账失败

### 重现步骤

```bash
1 有时候支付宝一次支出未能弹出窗口记账
2 下一次支出时自动记账会弹出两次窗口
3 如果模式选择了分类，记账窗口和分类窗口冲突了，无论是选择分类还是选择记账都会弹出钱迹失败文档
```

### 相关环境说明

自动记账 涅槃3.3.4
钱迹 3.2.1.13
lsposed 1.8.6 (6712) - Zygisk

### 日志内容

日志被淹没了

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该错误尚未被报告。

**Comment by dreamncn** [comment]
所以？你就从来都不想着看看错误文档写了什么吗？

**Comment by dreamncn** [comment]
No bug

**Comment by reov** [comment]
是miui的悬浮窗问题吗，每次都是记账悬浮窗在分类悬浮窗上面，点哪个都弹出钱迹错误的一个文档页面，懒人模式不分类就没有问题
在2023年6月5日六月 下午1:20，Ankio写道：
