### ISSUE TITLE
增加货币种类的选择

### ISSUE THREAD

**Issue by swirly0p** [dreamncn/Qianji_auto#190]
### 描述建议

本人使用多币种外币信用卡，消费记录里会出现多种货币，但目前的自动记账只能选择中文，能否增加钱迹货币种类的同步和选择

### 该功能带来的好处或者优点

```bash
方便多币种信用卡用户，更加智能
```

### 这不是重复的 issue

- [ ] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该功能尚未被报告。

**Comment by dreamncn** [comment]
#154
