### ISSUE TITLE
求教程

### ISSUE THREAD

**Issue by XDDD-hub** [dreamncn/Qianji_auto#192]
### 描述建议

现在版本已经更新了，但是教学视频还是老的，比如APP消息规则由(.*)变为(.*?)，希望大佬针对新版的记账插件出一版教程

### 该功能带来的好处或者优点

```bash
为新人带来操作上的便利
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该功能尚未被报告。

**Comment by joywqy** [comment]
同求

**Comment by dreamncn** [comment]
旧版的没空写了，等新版哈
