### ISSUE TITLE
分类怎么同步啊?

### ISSUE THREAD

**Issue by ioojcn** [dreamncn/Qianji_auto#196]
### 问题

好像就记得刚装APP时候同步一次.后续怎么同步分类啊.哭死了

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
https://auto.ankio.net/pages/f721e1/
