### ISSUE TITLE
自动记账模块云端规则

### ISSUE THREAD

**Issue by bufferist** [dreamncn/Qianji_auto#198]
### 问题

云端规则现在我无法添加了

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
更换网络

**Comment by bufferist** [comment]
![Uploading Screenshot_2023-11-07-22-51-15-160_cn.dreamn.qianji_auto.jpg…]()

我试了wifi  流量  clash都不行

**Comment by bufferist** [comment]
我用其他手机安装也是无法添加云端规则，软件显示云端没有规则

**Comment by dreamncn** [comment]
这是网络问题导致的，不是自动记账导致的。自动记账内置了几个加速源，可以在关于页面尝试切换

**Comment by bufferist** [comment]
好的，确实更换之后解决了，谢谢
