### ISSUE TITLE
上传至云端功能无法使用

### ISSUE THREAD

**Issue by Amarsimos** [dreamncn/Qianji_auto#199]
### 问题

自己创建识别规则后,上传至云端时,网页显示404 ,无法上传
这是网址   https://gitbot.ankio.net/submit/2?name=%E6%94%AF%E5%87%BA%EF%BC%88%E7%9B%AE%E5%89%8D%E4%BB%85%E6%B5%8B%E8%AF%95%E8%8A%B1%E5%91%97%EF%BC%89

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
可以直接在github提issue:

https://github.com/Auto-Accounting/AutoResource/issues/new?assignees=&labels=&projects=&template=%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6%E8%A7%84%E5%88%99%E6%8F%90%E4%BA%A4.md&title= <https://github.com/Auto-Accounting/AutoResource/issues/new?assignees=&labels=&projects=&template=%E8%87%AA%E5%8A%A8%E8%AE%B0%E8%B4%A6%E8%A7%84%E5%88%99%E6%8F%90%E4%BA%A4.md&title=>

—————————
Ankio 敬上
***@***.***
若无闲事挂心头，便是人间好时节。
