### ISSUE TITLE
推荐用智邮记微信小程序,可以实现招行信用卡等账单的自动记账到随手记app

### ISSUE THREAD

**Issue by bawfnje** [dreamncn/Qianji_auto#200]
### 描述建议

智邮记微信小程序本身不记录账单数据，它是将微信、支付宝以及招行等信用卡及借记卡的账单邮件自动记录到随手记app上。代替手工记账的。

### 该功能带来的好处或者优点

```bash
全自动，不需要手工干预
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该功能尚未被报告。

**Comment by dreamncn** [comment]
在我这刷什么存在感？
