### ISSUE TITLE
入群被拒绝

### ISSUE THREAD

**Issue by zlk1003493909** [dreamncn/Qianji_auto#201]
开发者您好，可能是由于我输错了qq号，导致入群被拒![Screenshot_2023-11-28-13-37-12-351_com.eg.android.AlipayGphone.jpg](https://github.com/Auto-Accounting/Qianji_auto/assets/49287244/60400e0c-1d58-4cc4-9ba5-fb1451f998fa)

**Comment by dreamncn** [comment]
要加群的qq是多少

**Comment by zlk1003493909** [comment]
1003493909

**Comment by dreamncn** [comment]
可以了，再试试
