### ISSUE TITLE
当前适配版本哪里有介绍？支付宝 微信 最新几个版本测试发现都没有适配？ 

### ISSUE THREAD

**Issue by Cxk4ng** [dreamncn/Qianji_auto#203]
### 问题

如题：
当前适配支付宝 微信版本是否有公告？公告信息在什么地方展示？
代码已经很久不更新了。。。。 我都怀疑项目是否还在维护中。。。

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该问题尚未被报告。

**Comment by dreamncn** [comment]
> 当前适配支付宝 微信版本是否有公告？公告信息在什么地方展示？

微信装个微x

支付宝默认是适配的

最近又开始写4.0了，可以关注这个仓库：https://github.com/Auto-Accounting/AutoAccounting

> 代码已经很久不更新了。。。。 我都怀疑项目是否还在维护中。。。

生活不能只有自动记账，还有诗和远方。
