### ISSUE TITLE
希望增加月度统计模块

### ISSUE THREAD

**Issue by Corybyte** [dreamncn/Qianji_auto#205]
### 描述建议

希望增加月度统计模块

### 该功能带来的好处或者优点

```bash
希望增加月度统计模块
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/dreamncn/Qianji_auto/issues)，以确保该功能尚未被报告。

**Comment by dreamncn** [comment]
这不是一个插件该做的事情，你应该反馈给【钱迹】
