### ISSUE TITLE
希望可以自定义云规则

### ISSUE THREAD

**Issue by LLXBH** [dreamncn/Qianji_auto#23]
希望可以自定义已有的规则，比如微信提现，备注太长了
微信零钱提现到账 - 你的零钱提现已到账至银行卡

想希望可以自定义

**Comment by dreamncn** [comment]
3.0已上线云规则，请耐心等待内测



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月31日(周一) 凌晨1:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dreamncn/Qianji_auto] 希望可以自定义云规则 (#23)




 
希望可以自定义已有的规则，比如微信提现，备注太长了
 微信零钱提现到账 - 你的零钱提现已到账至银行卡
 
想希望可以自定义
