### ISSUE TITLE
钱迹数据获取失败java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.mutangtech.qianji/databases/qianjiapp

### ISSUE THREAD

**Issue by NRD90M** [dreamncn/Qianji_auto#35]
钱迹数据获取失败java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/com.mutangtech.qianji/databases/qianjiapp
![微信图片_20210915090758](https://user-images.githubusercontent.com/30235128/133354011-ba4e5377-f159-42e6-be38-f7f6ccceca27.jpg)

**Comment by NRD90M** [comment]
![微信图片_20210915090758](https://user-images.githubusercontent.com/30235128/133353959-7ddbc6e1-28da-4379-b432-bb8c616dbd8e.jpg)
上传错了，不好意思

**Comment by dreamncn** [comment]
该问题已定位，在3.0内已修复。
