### ISSUE TITLE
支付宝(余额转到余额宝)

### ISSUE THREAD

**Issue by MSBSBX** [dreamncn/Qianji_auto#44]
{"data":[{"des":"编写:江\n说明:余额转入余额宝，支持自动手动","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"支付宝余额转入余额宝","tableList":{"shopRemark":"$3$1","money":"$1","fee":"","account2":"余额宝","account1":"余额","shopName":"$2","time":"","type":"2"},"text":"date:10月03日,unit:元,goto:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=20211003210500101000440091917288&bizType=YEB,ad:[],money:11.16,failTip:,infoTip:,title:余额宝-自动转入,actions:[name:,url:,name:查看详情,url:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=20211003210500101000440091917288&bizType=YEB],content:[title:付款方式：,content:余额,title:交易对象：,content:天弘基金管理有限公司,title:商品说明：,content:余额宝-自动转入],status:付款成功,amountTip:","regular":"money:(\\d+\\.\\d{2}),failTip:,infoTip:,title:(余额宝-自动转入|余额宝-单次转入),.*,content:余额,title:交易对象：,content:(.+?),title:商品说明：,content:(.+?)],status:付款成功,"}],"from":"app"}

**Comment by dreamncn** [comment]
云规则已经上架，重复了哦
