### ISSUE TITLE
微信规则(二维码收款)

### ISSUE THREAD

**Issue by MSBSBX** [dreamncn/Qianji_auto#53]
{"data":[{"des":"编写:江","identify":"app","fromApp":"com.tencent.mm","name":"③微信(二维码收款)","tableList":{"shopRemark":"$4$3","money":"$1","fee":"","account2":"","account1":"零钱","shopName":"","time":"","type":"1"},"text":"cache_user:微信红包,cache_user2:11,cache_paytools:零钱,isSend:0,title:卡片消息,content:msg:appmsg:extinfo:,lowurl:,sourcedisplayname:,showtype:1,title:微信支付收款0.03元(朋友到店),type:5,appattach:totallen:0,cdnthumburl:,aeskey:,attachid:,fileext:,cdnthumbaeskey:,content: t,content:,url:https://payapp.weixin.qq.com/payf2f/jumpf2fbill?timestamp=1633596104&openid=umCgDNAhfd_wvJBL1Ytm6mMct0lvm0ooaArEkgw3EVo=,soundtype:0,mmreader:template_detail:template_show_type:1,text_content:cover:,color:,text:,new_tmpl_type:0,line_content:topline:value:color:#000000,small_text_count:1,word:￥0.03,key:hide_dash_line:1,color:#888888,word:收款金额,lines:line:[value:color:#000000,word:今日第1笔收款，共计￥0.03,key:color:#888888,word:汇总,value:color:#FA962A,word:使用官方收款码收款送积分，积分换好礼，点击立即抢购,key:color:#888888,word:备注],opitems:opitem:[color:#000000,icon:,general_string:,weapp_path:pages/customerDetails/customerDetails.html?id=10000499012021100701316805372510&create_time=1633596103&report=msg_detail,display_line_number:0,url:,weapp_version:721,ext_id:,is_show_red_dot:0,hint_word:,weapp_username:gh_fac0ad4c321d@app,op_type:1,is_rich_text:0,word:查看详情,business_id:,weapp_state:0,color:#000000,icon:,general_string:,weapp_path:pages/report2/index/index.html?group=day&report=msg_report,display_line_number:0,url:,weapp_version:721,ext_id:,is_show_red_dot:0,hint_word:,weapp_username:gh_fac0ad4c321d@app,op_type:1,is_rich_text:0,word:查看经营报表,business_id:,weapp_state:0],show_type:1,publisher:nickname:微信收款助手,content: tt,username:gh_f0a92aa7146c,template_header:shortcut_icon_url:,hide_time:1,title:收款到账通知,show_icon_and_display_name:0,ignore_hide_title_and_time:1,hide_title_and_time:1,right_desc_name:,hide_icon_and_display_name_line:1,header_jump_url:,icon_url:,transaction_id:,first_color:#888888,title_color:,pay_style:1,finder_user_name:,pub_time:1633596104,header_jump_type:0,show_right_icon_and_desc_name:0,display_name:,finder_nonceid:,show_finder_feed_entry:0,display_name_desc:,right_icon_url:,finder_feed_thumnail:,first_data:10月07日 16:41,finder_feedid:,category:item:is_pay_subscribe:0,video_height:0,sources:source:name:微信收款助手,content: t,content: t,appmsg_like_type:0,video_width:0,recommendation:,title:微信支付收款0.03元(朋友到店),native_url:,content: t,cover:,weapp_version:721,vid:,pic_num:0,digest:收款金额￥0.03n汇总今日第1笔收款，共计￥0.03n备注使用官方收款码收款送积分，积分换好礼，点击立即抢购,cover_235_1:,weapp_username:gh_fac0ad4c321d@app,fileid:0,player:,cover_1_1:,del_flag:0,play_url:,shorturl:,pub_time:1633596104,pic_urls:,cover_16_9:,general_string:,template_op_type:1,weapp_path:pages/index/index.html,url:https://payapp.weixin.qq.com/payf2f/jumpf2fbill?timestamp=1633596104&openid=umCgDNAhfd_wvJBL1Ytm6mMct0lvm0ooaArEkgw3EVo=,tweetid:,play_length:0,comment_topic_id:0,music_source:0,longurl:,styles:topColor:,style:[color:#000000,range:4,5,font:s,color:#000000,range:12,15,font:s,color:#FA962A,range:30,25,font:s],itemshowtype:4,contentattr:0,weapp_state:0,show_complaint_button:0,count:1,name:微信收款助手,topnew:cover:,width:0,digest:收款金额￥0.03n汇总今日第1笔收款，共计￥0.03n备注使用官方收款码收款送积分，积分换好礼，点击立即抢购,content: ttt,height:0,type:0,content: tt,content: t,forbid_forward:0,notify_msg:,des:收款金额￥0.03n汇总今日第1笔收款，共计￥0.03n备注使用官方收款码收款送积分，积分换好礼，点击立即抢购,appid:,sourceusername:,sdkver:0,action:,template_id:hhBEwxiQAAY8HBHor5osXOl4zvANfBpjRKy_EkV__pg,thumburl:,contentattr:0,fromusername:gh_f0a92aa7146c,appinfo:appname:微信收款助手,version:0,isforceupdate:1,status:3,cache_money:￥0.01","regular":"title:微信支付收款(.*?)元((.*?)),.*汇总(.*?)n备注.*,appid:,"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
