### ISSUE TITLE
微信规则(商家转账)_修复

### ISSUE THREAD

**Issue by freetere** [dreamncn/Qianji_auto#55]
{"data":[{"des":"商家转账(暂行)\n适应大部分商家转账\n不识别的商家转账可在群里@freetere\n\n规则编写：freetere\n\n","identify":"app","fromApp":"com.tencent.mm","name":"微信规则(商家转账)","tableList":{"shopRemark":"商家转账[交易单号:$5]","money":"$1","fee":"","account2":"","account1":"$2","shopName":"$7","time":"$6","type":"1"},"text":"cache_user:微信红包,cache_user2:微信支付,cache_paytools:零钱,isSend:0,title:卡片消息,content:msg:appmsg:extinfo:,lowurl:,sourcedisplayname:,showtype:1,title:收款通知-来自商家转账,type:5,appattach:totallen:0,cdnthumburl:,aeskey:,attachid:,fileext:,cdnthumbaeskey:,content: t,content:,url:https://wx.tenpay.com/cgi-bin/mmpayweb-bin/jumpuserroll?trans_id=160893851221100810101004212542293031134995983&accid=085e9858e5c4941ca56669d03,soundtype:0,mmreader:template_detail:template_show_type:1,text_content:cover:,color:,text:,new_tmpl_type:0,line_content:topline:value:color:#000000,small_text_count:1,word:¥ 0.03,key:hide_dash_line:1,color:#888888,word:收款金额,lines:line:value:color:#000000,word:零钱,key:color:#888888,word:收款账户,opitems:opitem:color:#000000,icon:,general_string:,weapp_path:pages/mer-transfer/index/index.html?mp=4&trade_object_id=BgAAKREvyTlvThpU&time=1633681661,display_line_number:0,url:,weapp_version:143,ext_id:,is_show_red_dot:0,hint_word:进入记账本,weapp_username:gh_82ed079da8ca@app,op_type:1,is_rich_text:0,word:收款统计,business_id:,weapp_state:0,show_type:1,publisher:nickname:微信支付,content: tt,username:wxzhifu,template_header:shortcut_icon_url:,hide_time:1,title:收款通知-来自商家转账,show_icon_and_display_name:1,ignore_hide_title_and_time:1,hide_title_and_time:1,right_desc_name:,hide_icon_and_display_name_line:0,header_jump_url:,icon_url:http://wx.qlogo.cn/mmhead/Q3auHgzwzM6AdhMk9qMmtVsk85f0xCxicKLXqq5X3LgtCiav0fZJic9uw/,transaction_id:10101296375172110086304089102121,first_color:,title_color:,pay_style:1,finder_user_name:,pub_time:1633681671,header_jump_type:0,show_right_icon_and_desc_name:0,display_name:拼多多,finder_nonceid:,show_finder_feed_entry:0,display_name_desc:,right_icon_url:,finder_feed_thumnail:,first_data:,finder_feedid:,category:item:is_pay_subscribe:0,video_height:0,sources:source:name:微信支付,content: t,content: t,appmsg_like_type:0,video_width:0,recommendation:,title:收款通知-来自商家转账,native_url:,content: t,cover:,weapp_version:0,vid:,pic_num:0,digest:收款金额¥ 0.03n收款账户零钱,cover_235_1:,weapp_username:,fileid:0,player:,cover_1_1:,del_flag:0,play_url:,shorturl:,pub_time:1633681671,pic_urls:,cover_16_9:,general_string:,template_op_type:0,weapp_path:,url:https://wx.tenpay.com/cgi-bin/mmpayweb-bin/jumpuserroll?trans_id=160893851221100810101004212542293031134995983&accid=085e9858e5c4941ca56669d03,tweetid:,play_length:0,comment_topic_id:0,music_source:0,longurl:,styles:topColor:,style:[color:#000000,range:4,6,font:s,color:#000000,range:15,2,font:s],itemshowtype:4,contentattr:0,weapp_state:0,show_complaint_button:0,count:1,name:微信支付,topnew:cover:,width:0,digest:收款金额¥ 0.03n收款账户零钱,content: ttt,height:0,type:0,content: tt,content: t,forbid_forward:0,notify_msg:,des:收款金额¥ 0.03n收款账户零钱,appid:,sourceusername:,sdkver:0,action:,template_id:XfnDbpXCnUTZyZK292FiQuHOpYG9qzWnEJhXTfQ3RTY,thumburl:,contentattr:0,fromusername:gh_3dfda90e39d6,appinfo:appname:微信支付,version:0,isforceupdate:1,status:3,cache_money:￥0.01","regular":"title:卡片消息,.*title:收款通知-来自商家转账,.*?word:¥(.*?),key:hide_dash_line:1,color:.*?,word:收款金额,lines:line:\\[?value:color:.*?,word:(.*?),key:color:.*?,word:收款账户,(value:color:.*?,word:(.*?),key:color:.*?,word:转账备注\\]?,)?opitems.*?transaction_id:(.*?),.*?pub_time:(.*?),.*?display_name:(.*?),"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
