### ISSUE TITLE
短信识别规则 -中国银行网上支付

### ISSUE THREAD

**Issue by GStarmin** [dreamncn/Qianji_auto#56]
{"data":[{"des":"中国银行短信识别 by Starmin","identify":"sms","fromApp":"95566","name":"中国银行网上支出","tableList":{"shopRemark":"","money":"$3","fee":"0","account2":"","account1":"中国银行","shopName":"","time":"$2","type":"0"},"text":"您的借记卡账户1000，于10月06日网上支付支取人民币9.9元,交易后余额9999.9【中国银行】","regular":"您的借记卡([\\s\\S]*)，于([\\s\\S]*)网上支付支取人民币([\\s\\S]*)元,交易后余额([\\s\\S]*)【中国银行】"}],"from":"sms"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
