### ISSUE TITLE
支付宝规则(退款暂行)

### ISSUE THREAD

**Issue by freetere** [dreamncn/Qianji_auto#57]
{"data":[{"des":"\n规则编写：freetere\n数据提供：狗互跪互相汪","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"支付宝规则(退款暂行)","tableList":{"shopRemark":"【支付宝退款】$5[订单号：$3]","money":"$2","fee":"","account2":"","account1":"$4","shopName":"","time":"$1","type":"1"},"text":"date:10月09日,unit:元,goto:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=2021100922001164841411230175_2166103728120123003&bizType=TRADE,ad:[],money:10.00,failTip:,infoTip:,title:退款通知,actions:[name:,url:,name:查看详情,url:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=2021100922001164841411230175_2166103728120123003&bizType=TRADE],content:[title:退款去向：,content:花呗,title:退款说明：,content:退款-笔记本导热热管散热铜管DIY散热器风扇铜管烧结管CPU显卡散热专用],status:退款到账通知,amountTip:","regular":"date:(.*?),unit:元,.*?money:(.*?),.*?title:退款通知,actions:.*tradeNO=(.*?)&.*,content:\\[title:退款去向：,content:(.*?),title:退款说明：,content:(.*?)\\],status:退款到账通知,amountTip:"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
