### ISSUE TITLE
网商银行-余利宝收益

### ISSUE THREAD

**Issue by WinverLemon** [dreamncn/Qianji_auto#58]
{"data":[{"des":"网商银行-余利宝收益\n规则编写：Lemon\n数据提供：阿狸","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"支付宝规则(网商银行-余利宝收益)","tableList":{"shopRemark":"$1月$2日收益","money":"$3","fee":"","account2":"","account1":"余利宝","shopName":"$4-余利宝","time":"","type":"1"},"text":"hiddenSumFlag:N,expireLink:https://render.alipay.com/p/f/fd-jblxfp45/pages/home/index.html,icon:http://mdn.alipayobjects.com/afts/img/o4RRXj6ORd2_HuMFHv91SgAAACMAAQQD/original?bz=mwalletmng_[pixelWidth]x.jpeg,link:alipays://platformapi/startapp?appId=66666708&url=https%3A%2F%2Frender.alipay.com%2Fp%2Fh5%2Falipay-yulibao%2Fwww%2Findex.html%3FchInfo%3Dfeed,assistName2:收益时间,assistName3:温馨提醒,assistName1:收益金额,subscribeConfig:1,title:网商银行,templateId:WALLET-FWC@remindDefaultText,content:昨日收益已到账,linkName:查看详情,assistMsg3:支付宝转入额度又提高啦，可免费提现,assistMsg2:10-08,assistMsg1:+24.98,gmtValid:1949260686318,sceneExt:sceneTemplateId:WALLET-FWC@remindDefaultText,sceneUrl:alipays://platformapi/startapp?appId=20000042&publicBizType=LIFE_APP&sourceId=notifications&publicId=2015121400973550,sceneType:lifePublic,forwardLifePublicMsg:N,sceneName:网商银行,sceneId:2015121400973550,sceneIcon:http://mdn.alipayobjects.com/afts/img/o4RRXj6ORd2_HuMFHv91SgAAACMAAQQD/original?bz=mwalletmng_[pixelWidth]x.jpeg,sceneExtInfo:,sceneTitle:进入生活号,homePageTitle:余利宝收益到账啦,imageUrl:,buttonLink:alipays://platformapi/startapp?appId=66666708&url=https%3A%2F%2Frender.alipay.com%2Fp%2Fh5%2Falipay-yulibao%2Fwww%2Findex.html%3FchInfo%3Dfeed,extra:昨日收益已到账,cardAdInfo:p10:bizMonitor:marketingUniqueId:MUed90c84a487e4c8f92fde430cb6e544c,style:recommendAssistLine,marketingItemId:MI386dac05045444408900398be6169116,recommendTemplateId:recommendAssistLine,viewInfo:assistMsg:自动转入3次可领大奖,btnBorderColor:#FFAF87,btnText:去领取,btnTextColor:#FF6010,assistMsgColor:#FF6010,actionUrl:https://render.mybank.cn/p/c/18d7dhah4ev4,assistName:本次奖励,expireTime:1665263886333,clientPositionId:p10,minClientVersion:10.1.98","regular":"assistMsg2:(\\d+)-(\\d+),assistMsg1:\\+(\\d+\\.\\d{2}),.*sceneName:(.*?),.*余利宝收益到账啦,"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
