### ISSUE TITLE
支付宝规则(个人二维码收款)

### ISSUE THREAD

**Issue by MSBSBX** [dreamncn/Qianji_auto#61]
{"data":[{"des":"编写:江","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"③支付宝(个人二维码收款)","tableList":{"shopRemark":"$1","money":"$2","fee":"","account2":"","account1":"余额","shopName":"","time":"","type":"1"},"text":"expireLink:https://render.alipay.com/p/f/fd-jblxfp45/pages/home/index.html,assistName2:备注,assistName3:,assistName1:经营数据,templateId:WALLET-FWC@remindDefaultText,title:商家服务·收款到账,linkName:查看订单详情,assistMsg3:,assistMsg2:用收钱码收钱，安全有保障,gmtValid:1641548757697,assistMsg1:今日第1笔收入，共计¥500.00,assistMsg5:,assistName4:,imageUrl:,assistMsg4:,assistName5:,buttonLink:https://render.alipay.com/p/z/merchant-mgnt/simple-order.html,extra: 收款金额￥500.00","regular":"title:商家服务·收款到账,.*,assistMsg1:(.*?),.*?,extra: 收款金额￥(\\d+\\.\\d{2})"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
