### ISSUE TITLE
支付宝规则(外卖+淘宝退款)

### ISSUE THREAD

**Issue by MSBSBX** [dreamncn/Qianji_auto#62]
{"data":[{"des":"编写:江\n说明:饿了么外卖+淘宝退款","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"③支付宝(外卖+淘宝退款)","tableList":{"shopRemark":"订单编号:『$3』","money":"$1","fee":"","account2":"","account1":"$4","shopName":"$5","time":"","type":"1"},"text":"date:10月08日,unit:元,goto:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=2021100822001169441455242006_2167261167215321168&bizType=TRADE,ad:[],money:60.00,failTip:,infoTip:,title:退款通知,actions:[name:,url:,name:查看详情,url:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=2021100822001169441455242006_2167261167215321168&bizType=TRADE],content:[title:退款去向：,content:余额宝,title:退款说明：,content:退款-篮球服套装免费定制支持来图定做男女篮球训练服无袖宽松上衣 等多件],status:退款到账通知,amountTip:","regular":"money:(\\d+\\.\\d{2}),.*?:\\[.*tradeNO=(.*?)_(.*?)&bizType=TRADE],content:\\[.*content:(.*?),title:退款说明：,content:退款-(.*?)]"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
