### ISSUE TITLE
支付宝规则(阿里巴巴等调用付款)

### ISSUE THREAD

**Issue by YifePlayte** [dreamncn/Qianji_auto#63]
{"data":[{"des":"阿里巴巴等软件内付款，仅测试过阿里巴巴\n规则编写：YifePlayte","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"支付宝规则(阿里巴巴等调用付款)","tableList":{"shopRemark":"$5","money":"$2","fee":"","account2":"","account1":"$3","shopName":"$4","time":"","type":"0"},"text":"date:10月10日,unit:元,goto:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=2021101022001840051454059318_11200600721101088733740123799&bizType=TRADE,ad:[],money:37.00,failTip:,infoTip:,title:付款成功,actions:[name:AA收款,url:alipays://platformapi/startapp?appId=60000154&url=%2Fwww%2Findex%2Fcreate.htm%3Fsource%3Dbill_01%26amount%3D37.00%26remark%3D%E5%85%A8%E6%AC%BE%E4%BA%A4%E6%98%93%EF%BC%9A%E9%80%82%E7%94%A8%E7%BA%A2%E7%B1%B3K40%E9%9B%BE%E9%9D%A2%E6%BB%A1%E7%89%88%E9%92%A2%E5%8C%96%E7%8E%BB%E7%92%83%E8%86%9C2.5D%E7%94%B5%E7%AB%9E%E8%9A%80%E5%88%BB%E7%A3%A8%E7%A0%82%E4%BA%AE%E8%BE%B9%E4%BF%9D%E6%8A%A4%E8%B4%B4%E8%86%9C,name:查看详情,url:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=2021101022001840051454059318_11200600721101088733740123799&bizType=TRADE],content:[title:付款方式：,content:中国工商银行储蓄卡(8848),title:交易对象：,content:朱春淼,title:商品说明：,content:全款交易：适用红米K40雾面满版钢化玻璃膜2.5D电竞蚀刻磨砂亮边保护贴膜],status:付款成功,amountTip:","regular":"date:(.*),unit:元,goto:.*,ad:.*,money:(.*),failTip:,infoTip:,title:付款成功,actions:\\[.*\\],content:\\[title:付款方式：,content:(.*),title:交易对象：,content:(.*),title:商品说明：,content:(.*)\\],status:付款成功,amountTip:"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
