### ISSUE TITLE
支付宝规则(赚钱红包-吱信)

### ISSUE THREAD

**Issue by freetere** [dreamncn/Qianji_auto#64]
{"data":[{"des":"适用于支付宝-赚钱红包发放的现金奖励\n可上支付宝搜 715238036\n白嫖线下消费红包并支持作者 \n\n规则编写：freetere\n\n","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"支付宝规则(吱信)","tableList":{"shopRemark":"$4[交易单号:$2]","money":"$1","fee":"","account2":"","account1":"余额","shopName":"$3","time":"$5","type":"1"},"text":"date:10月10日,unit:元,goto:alipays://platformapi/startapp?appId=66666676&appClearTop=false&url=%2Fwww%2Findex.html%3FtradeNo%3D20211010110070001506360076729056%26bizType%3DBIZFUND%26appClearTop%3Dfalse%26startMultApp%3DYES,money:0.70,title:支付助手,actions:[name:查看详情,url:alipays://platformapi/startapp?appId=66666676&appClearTop=false&url=%2Fwww%2Findex.html%3FtradeNo%3D20211010110070001506360076729056%26bizType%3DBIZFUND%26appClearTop%3Dfalse%26startMultApp%3DYES],content:[title:付款方：,content:吱信（上海）网络技术有限公司,title:转账备注：,content:支付宝发红包，你赚现金奖励,title:到账时间：,content:2021-10-10 18:16],status:奖励到账成功","regular":"money:(\\d+\\.\\d+?),title:支付助手,actions:.*?tradeNo%3D(.*?)%26.*?,content:\\[title:付款方：,content:(.*?),title:转账备注：,content:(.*?),title:到账时间：,content:(.*?)\\],status:(收到一笔奖励|奖励到账成功)"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
