### ISSUE TITLE
未能读取支付宝通知

### ISSUE THREAD

**Issue by cyp0633** [dreamncn/Qianji_auto#65]
支付宝Apple Music自动续订通知。怀疑是被MIUI归类为不重要通知造成（如图1），但在将其设为重要之后，在自动记账中刷新app通知，仍不能读取到那条通知（如图2）。
已开启支付宝监控，其他通知能够正常读取。
如果需要我提供更多信息，请回复，谢谢
![IMG_20211010_225707.jpg](https://user-images.githubusercontent.com/16500188/136701458-1b8af966-1912-4e38-b1cb-cecdc8614a23.jpg)![Screenshot_2021-10-10-22-56-40-496_cn.dreamn.qianji_auto.jpg](https://user-images.githubusercontent.com/16500188/136701456-5c24e2fd-3413-485d-b8b7-75e5eede272d.jpg)

**Comment by dreamncn** [comment]
beta11以上版本，在【关于】中，连续五次点击logo打开调试模式，再试，并发送日志给我。
