### ISSUE TITLE
支付宝账单规则

### ISSUE THREAD

**Issue by ferstar** [dreamncn/Qianji_auto#66]
{"data":[{"des":"by ferstar","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"一个比较暴力的支付宝账单规则","tableList":{"shopRemark":"账单号: $1","money":"$2","fee":"","account2":"","account1":"$3","shopName":"$5 - $4","time":"","type":"0"},"text":"date:10月10日,unit:元,goto:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=20211010042830291&bizType=PPAY,ad:[],money:12.12,failTip:,infoTip:,title:付款成功,actions:[name:,url:,name:查看详情,url:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=2021101004200102001085830291&bizType=PPAY],content:[title:付款方式：,content:招商银行信用卡(9527),title:交易对象：,content:lol,title:商品说明：,content:亲情卡],status:付款成功,amountTip:","regular":"tradeNO=(\\d+).*?money:(.*?),.*付款方式.*?content:(.*?),.*?交易对象.*?content:(.*?),.*?商品说明.*content:(.*?)\\]?,"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
