### ISSUE TITLE
支付宝赚钱红包规则

### ISSUE THREAD

**Issue by NewBody-LC** [dreamncn/Qianji_auto#67]
{"data":[{"des":"支付宝赚钱红包活动识别","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"赚钱红包💰","tableList":{"shopRemark":"$3","money":"$1","fee":"","account2":"","account1":"支付宝","shopName":"$2","time":"$4","type":"1"},"text":"date:10月11日,unit:元,goto:alipays://plbatformapi/startapp?appId=66666676&appClearTop=false&url=%2Fwww%2Findex.html%3FtradeNo%3D20211011110070001506580075513413%26bizType%3DBIZFUND%26appClearTop%3Dfalse%26startMultApp%3DYES,money:3.09,title:支付助手,actions:[name:查看详情,url:alipays://platformapi/startapp?appId=66666676&appClearTop=false&url=%2Fwww%2Findex.html%3FtradeNo%3D20211011110070001506580075513413%26bizType%3DBIZFUND%26appClearTop%3Dfalse%26startMultApp%3DYES],content:[title:付款方：,content:吱信（上海）网络技术有限公司,title:转账备注：,content:支付宝发红包，你赚现金奖励,title:到账时间：,content:2021-10-11 08:50],status:奖励到账成功","regular":"date:.*money:(\\d+\\.\\d+)?.*content:(.*),t.*?content:(.*)?,t.*content:(.*)],status:(.*)"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
