### ISSUE TITLE
突然的自我异常

### ISSUE THREAD

**Issue by AMNOTSR** [dreamncn/Qianji_auto#69]
verCode:涅槃 3.0.0 beta6

error:
pthread_create (1040KB stack) failed: Try again

stackTrace:
1.java.lang.Thread.nativeCreate(Native Method)
2.java.lang.Thread.start(Thread.java:733)
3.cn.dreamn.qianji_auto.utils.runUtils.Task.onThread(Task.java:58)
4.cn.dreamn.qianji_auto.utils.runUtils.Log.i(Log.java:70)
5.cn.dreamn.qianji_auto.utils.runUtils.Log.i(Log.java:62)
6.cn.dreamn.qianji_auto.core.helper.Inner.HelpService.onAccessibilityEvent(HelpService.java:105)
7.android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1538)
8.android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1724)
9.com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
10.android.os.Handler.dispatchMessage(Handler.java:106)
11.android.os.Looper.loop(Looper.java:207)
12.android.app.ActivityThread.main(ActivityThread.java:6820)
13.java.lang.reflect.Method.invoke(Native Method)
14.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
15.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by dreamncn** [comment]
beta 10已经修复
