### ISSUE TITLE
微信▪公众号▪平安银行▪支出

### ISSUE THREAD

**Issue by nov0000** [dreamncn/Qianji_auto#70]
digest:尊敬的客户：nnn您尾号(\d+)的信用卡的最新交易信息n交易时间：.*n交易商户：(.*)-(.*)n交易类型：消费n交易金额：RMB(.*)nnrn交易成功，现剩余可用额度.*n

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
