### ISSUE TITLE
微信▪公众号▪招商银行▪支出(自用的公众号规则上传保存一下）

### ISSUE THREAD

**Issue by nov0000** [dreamncn/Qianji_auto#71]
尊敬的.*:nn您尾号(\d+)的信用卡最新交易信息n交易时间：.*n交易商户：(.*)-(.*)n交易类型：消费n交易金额：人民币 (.*)元nn★

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
