### ISSUE TITLE
京东购物后微信通知消息的识别

### ISSUE THREAD

**Issue by gongchensu** [dreamncn/Qianji_auto#72]
{"data":[{"des":"识别京东付款，微信通知的消息","identify":"app","fromApp":"com.tencent.mm","name":"微信付款（京东识别）","tableList":{"shopRemark":"$4，订单号:$2","money":"$3","fee":"","account2":"","account1":"$6","shopName":"","time":"$5","type":"0"},"text":"cache_user:蔚蓝电动,cache_user2:大美美💃🏻💃🏻 ,cache_paytools:浦发银行信用卡(1823),isSend:0,title:卡片消息,content:msg:appmsg:extinfo:,lowurl:,sourcedisplayname:,showtype:1,title:付款成功通知,type:5,appattach:totallen:0,cdnthumburl:,aeskey:,attachid:,fileext:,cdnthumbaeskey:,content: t,content:,url:https://wqs.jd.com/order/n_detail_v2.shtml?deal_id=225162499982&bid=&deal_refer_uin=0&new=1&jddeal=1&PTAG=17005.9.185&source=jdgzh_jd&apprecall=1&sceneval=2&send_info=22238438FEFC1937B65CC12C18AC4A17F6E5756A77A8D4687B70C4B8CCAC6EEB,soundtype:0,mmreader:template_detail:template_show_type:1,text_content:cover:,color:,text:,new_tmpl_type:0,line_content:lines:line:[value:color:#333333,word:￥155.90元,key:color:#888888,word:实付金额：,value:color:#333333,word:百富帝（byford）四件套纯棉家纺 床上用品床单枕套双人全棉斜纹套件1.5/1.8米床被套200*230 海豚湾,key:color:#888888,word:商品详情：,value:color:#333333,word:四川南充市仪陇县新政镇金鱼街首座11栋702,key:color:#888888,word:收货地址：,value:color:#333333,word:225162499982,key:color:#888888,word:订单编号：,value:color:#e4393c,word:恭喜！您获得评论抽手机特权，回复“1”参与,key:color:#888888,word:备注：],opitems:opitem:color:#000000,icon:,general_string:,weapp_path:,display_line_number:0,url:https://wqs.jd.com/order/n_detail_v2.shtml?deal_id=225162499982&bid=&deal_refer_uin=0&new=1&jddeal=1&PTAG=17005.9.185&source=jdgzh_jd&apprecall=1&sceneval=2&send_info=22238438FEFC1937B65CC12C18AC4A17F6E5756A77A8D4687B70C4B8CCAC6EEB,weapp_version:0,ext_id:,is_show_red_dot:0,hint_word:,weapp_username:,op_type:0,is_rich_text:0,word:查看详情,business_id:,weapp_state:0,show_type:0,publisher:nickname:京东JD.COM,content: tt,username:JD,template_header:first_color:,title_color:,pub_time:1633942397,first_data:尊敬的京东用户，您的京东订单已经成功付款啦~正在秒速安排发货，尽心尽力，不愿让你等快递。n,title:付款成功通知,show_complaint_button:1,category:item:is_pay_subscribe:0,video_height:0,sources:source:name:京东JD.COM,content: t,content: t,appmsg_like_type:0,video_width:0,recommendation:,title:付款成功通知,native_url:,content: t,cover:,weapp_version:0,vid:,pic_num:0,digest:尊敬的京东用户，您的京东订单已经成功付款啦~正在秒速安排发货，尽心尽力，不愿让你等快递。nn实付金额：￥155.90元n商品详情：百富帝（byford）四件套纯棉家纺 床上用品床单枕套双人全棉斜纹套件1.5/1.8米床被套200*230 海豚湾n收货地址：四川南充市仪陇县新政镇金鱼街首座11栋702n订单编号：225162499982n恭喜！您获得评论抽手机特权，回复“1”参与,cover_235_1:,weapp_username:,fileid:0,player:,cover_1_1:,del_flag:0,play_url:,shorturl:,pub_time:1633942397,pic_urls:,cover_16_9:,general_string:,template_op_type:0,weapp_path:,url:https://wqs.jd.com/order/n_detail_v2.shtml?deal_id=225162499982&bid=&deal_refer_uin=0&new=1&jddeal=1&PTAG=17005.9.185&source=jdgzh_jd&apprecall=1&sceneval=2&send_info=22238438FEFC1937B65CC12C18AC4A17F6E5756A77A8D4687B70C4B8CCAC6EEB,tweetid:,finder_feed:,play_length:0,comment_topic_id:0,music_source:0,longurl:,styles:topColor:#FF0000,style:[color:#b99434,range:0,45,font:s,color:#333333,range:51,8,font:s,color:#333333,range:65,57,font:s,color:#333333,range:128,22,font:s,color:#333333,range:156,12,font:s,color:#e4393c,range:169,21,font:s],itemshowtype:4,contentattr:0,weapp_state:0,show_complaint_button:1,count:1,name:京东JD.COM,topnew:cover:,width:0,digest:尊敬的京东用户，您的京东订单已经成功付款啦~正在秒速安排发货，尽心尽力，不愿让你等快递。nn实付金额：￥155.90元n商品详情：百富帝（byford）四件套纯棉家纺 床上用品床单枕套双人全棉斜纹套件1.5/1.8米床被套200*230 海豚湾n收货地址：四川南充市仪陇县新政镇金鱼街首座11栋702n订单编号：225162499982n恭喜！您获得评论抽手机特权，回复“1”参与,content: ttt,height:0,type:0,content: tt,content: t,forbid_forward:0,notify_msg:,des:尊敬的京东用户，您的京东订单已经成功付款啦~正在秒速安排发货，尽心尽力，不愿让你等快递。nn实付金额：￥155.90元n商品详情：百富帝（byford）四件套纯棉家纺 床上用品床单枕套双人全棉斜纹套件1.5/1.8米床被套200*230 海豚湾n收货地址：四川南充市仪陇县新政镇金鱼街首座11栋702n订单编号：225162499982n恭喜！您获得评论抽手机特权，回复“1”参与,appid:,sourceusername:,sdkver:0,action:,template_id:eU96zZORNEOFvaLC4x6g0smnw9WMPyxaumFTLA5BzUw,thumburl:,contentattr:0,fromusername:qqwanggou001,appinfo:appname:京东JD.COM,version:0,isforceupdate:1,status:3,cache_money:￥299.00","regular":"cache_user:.*?,cache_paytools:(.*?),.*?,title:付款成功通知,.*,url:.*deal_id=(\\d+)&.*,word:￥(\\d+\\.\\d{2})元.*,word:实付金额.*,word:(.*),key:.*word:商品详情.*,pub_time:(\\d+),.*sources:source:name:(.*?),content:.*content:.*"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
