### ISSUE TITLE
后台运行过程中报错

### ISSUE THREAD

**Issue by Xionghaizi001** [dreamncn/Qianji_auto#73]
verCode:涅槃 3.0.0 beta6

error:
Failed to allocate a 1686464 byte allocation with 846480 free bytes and 826KB until OOM, target footprint 268435456, growth limit 268435456

stackTrace:
1.java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
2.java.lang.StringBuilder.toString(StringBuilder.java:413)
3.cn.dreamn.qianji_auto.core.helper.Inner.HelpService.onAccessibilityEvent(HelpService.java:107)
4.android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2081)
5.android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2284)
6.com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
7.android.os.Handler.dispatchMessage(Handler.java:106)
8.android.os.Looper.loop(Looper.java:223)
9.android.app.ActivityThread.main(ActivityThread.java:7846)
10.java.lang.reflect.Method.invoke(Native Method)
11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

**Comment by dreamncn** [comment]
beta10已修复
