### ISSUE TITLE
hui自用

### ISSUE THREAD

**Issue by grimm-yh** [dreamncn/Qianji_auto#74]
{"data":[{"des":"自用","name":"自用规则","tableList":"","regular":"var sRemark = shopName+shopRemark+source, \naRegs=[];\nswitch (type) {\n    case \"报销\":\n    case \"支出\":\n        var aOutRegs=[\n\t\t\t{\"bkName\":\"食品\", \"reg\": /[餐食饭炸烤蒸炒煨炖煮汤面烧]|饿了么|小吃|饺子|美团订单|外卖|(?=便)|(?=果)/i},\n\t\t\t{\"bkName\":\"储值\", \"reg\": /加速器|(1号|畅读|影城)卡|[^蚁]会员|QQ(美化|号)|vip|迅雷|爱奇艺|优酷|腾讯视频|软件.*安装|(激活|注册)码|([高升]级|专业|付费|终[生身级]|增强|完整|永久)版|\\bP(ro|lus)\\|游戏|game|Steam|育碧|点券|米哈游|电信|联通|移动/i},\n\t\t\t{\"bkName\":\"数码\", \"reg\": /手机|电脑|电视|冰箱|洗衣机|空调|NOKIA|诺基亚|MOTO|摩托罗拉|Samsung|三星|索尼爱立信|Apple|苹果|Philips|飞利浦|lenovo|联想|LGSharp|夏普|多普达|金立|Amoi|夏新|Bird|波导|纽曼|Haier|海尔|TCL|HP|惠普|BenQ|明基|OPPO|Konka|康佳|CECT|HEDY|七喜|CoolPAD|酷派|ASUS|华硕|Mio宇达电通|琦基|ZTE|中兴|MEIZU|魅族|UT斯达康|BlackBerry|黑莓|Alcatel|阿尔卡特|大显|HKC|弘谷电|艾美讯|amsam|恒基伟业|Palm|RIM|OKWAP|英华达|天语|小米|华为|一加|联想|OPPO|vivo|诺基亚|华硕|惠普|三星|索尼|金士顿|闪迪|七彩虹|英特尔|Intel|AMD|松下|美的|格力/i},\n            {\"bkName\":\"生活用品\", \"reg\": /七件事|超市|便利|.*客隆|家.*福|快乐惠|世纪联华|联华超市|大润发|华润万家|苏果|沃尔玛|物美|新一佳|好又多|华联|文峰大世界|TESCO乐购|易初莲花|麦德龙|中百连锁仓储|人人乐|家家悦|潍坊百货|欧尚|永辉|武商量贩|新华都|步步高商业|永旺|红旗连锁|三江购物|互惠|美廉美|百佳超市|易买得|维客|美特好|保龙仓|华普|利客来|良友金伴|美宜佳|华冠|家润多|华之友|好家乡|惠友|民生家乐|思达|雅家乐|天惠|新江厦|喜洋洋|乐尔乐/},\n\t\t\t{\"bkName\":\"租房家具\",\"reg\": /[电水]费|(燃|液化)气/},\n            {\"bkName\":\"外部刚需\", \"reg\": /地铁|公交|滴滴|高德|出租车|的士|打的|代驾|铁路|火车|高铁|列车/},\n            {\"bkName\":\"特殊消费\", \"reg\":/(红包|转账)给*|保[险单]|相互宝/},\n            {\"bkName\":\"外貌服饰\", \"reg\": /[衣裤鞋袜帽穿戴]|[男女]装|牛仔|耐克|nike|阿迪|361[度°]|鸿星尔克|特步|李宁|美特斯邦威|优衣库|以纯发廊|美发/i},\n\t\t\t{\"bkName\":\"文娱\", \"reg\": /打印|课程|教[材辅育程你]|讲[解义]|学会|入门到精通|慕课|学院|医视时代|医脉通|新东方在线|潭州课堂沪江小D|影[城院]|(电影|淘票)票|猫眼电影|中影|王府井|cgv|潇湘国际/i},\n\t\t\t{\"bkName\":\"医药\", \"reg\": /医(院|馆|.?室)|药[店房号]|诊所|卫生(服务(中心|站)|[院所室])/}\n           ];\n        aRegs = aRegs.concat(aOutRegs);\n        aOutRegs = null;\n        break;\n    case \"收入\":\n        var aInRegs=[\n\t\t\t{\"bkName\":\"基本工资\", \"reg\":/(工资|津贴)/},\n\t\t\t{\"bkName\":\"额外收入\", \"reg\":/(余[额利]宝).*收益|收.*(红包|转账)|退款/}\n           ];\n        aRegs = aRegs.concat(aInRegs);\n        aInRegs = null;\n        break;\n    default:\n        aRegs=[];\n        break;\n}\n\nvar result = \"其他\";\nfor (var i = 0 ,len = aRegs.length ; i<len; i++) {\n\tif (aRegs[i].reg.test(sRemark)){\n\t\tresult = aRegs[i].bkName;\n\t\tbreak;\n\t}\n}\nreturn result;"}],"from":"category"}

**Comment by dreamncn** [comment]
规则请提交到 http://gitbot.ankio.net/submit/2
