### ISSUE TITLE
打开日志报错

### ISSUE THREAD

**Issue by grimm-yh** [dreamncn/Qianji_auto#75]
verCode:涅槃 3.0.0 beta6

error:
Failed to allocate a 213909512 byte allocation with 25165824 free bytes and 47MB until OOM, target footprint 378209520, growth limit 402653184

stackTrace:
1.java.util.Arrays.copyOf(Arrays.java:3257)
2.java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
3.java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
4.java.lang.StringBuilder.append(StringBuilder.java:137)
5.cn.dreamn.qianji_auto.ui.fragment.data.LogFragment.lambda$loadFromData$3$LogFragment(LogFragment.java:204)
6.cn.dreamn.qianji_auto.ui.fragment.data.-$$Lambda$LogFragment$4ejIvEOWbaOUZK9nLnfOIcwaiss.getLog(Unknown Source:2)
7.cn.dreamn.qianji_auto.utils.runUtils.Log.lambda$getAll$5(Log.java:130)
8.cn.dreamn.qianji_auto.utils.runUtils.-$$Lambda$Log$VfG2CmrEeUdcYxm2W6pybRzd-VU.run(Unknown Source:2)
9.cn.dreamn.qianji_auto.utils.runUtils.Task.onThread(Task.java:60)
10.cn.dreamn.qianji_auto.utils.runUtils.Log.getAll(Log.java:113)
11.cn.dreamn.qianji_auto.ui.fragment.data.LogFragment.lambda$loadFromData$4$LogFragment(LogFragment.java:192)
12.cn.dreamn.qianji_auto.ui.fragment.data.-$$Lambda$LogFragment$U3jZytV6aDFAAuaN9_nV8fpJ6XI.run(Unknown Source:2)
13.java.lang.Thread.run(Thread.java:929)

**Comment by dreamncn** [comment]
beta10已修复
