### ISSUE TITLE
支付宝小荷包

### ISSUE THREAD

**Issue by XueJinglin** [dreamncn/Qianji_auto#76]
{"data":[{"des":"","identify":"app","fromApp":"com.eg.android.AlipayGphone","name":"支付宝小荷包","tableList":{"shopRemark":"($1)$6[订单号: $2]","money":"$3","fee":"","account2":"$5","account1":"$4","shopName":"支付宝","time":"","type":"2"},"text":"date:10月16日,unit:元,goto:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=20211016110075001506760041208480&bizType=BIZFUND,ad:[],money:3000.00,failTip:,infoTip:,title:转入成功,actions:[name:AA收款,url:alipays://platformapi/startapp?appId=60000154&url=%2Fwww%2Findex%2Fcreate.htm%3Fsource%3Dbill_99%26amount%3D3000.00%26remark%3D%E6%94%AF%E4%BB%98%E5%AE%9D%E5%B0%8F%E8%8D%B7%E5%8C%85-10%E6%9C%88%E4%BB%BD%E6%94%92%E9%92%B1,name:查看详情,url:alipays://platformapi/startapp?appId=20000003&actionType=toBillDetails&tradeNO=202110160075001506760041208480&bizType=BIZFUND],content:[title:付款方式：,content:中国建设银行储蓄卡(6534),title:对方账户：,content:支付宝小荷包(哈哈哈的小荷包),title:转账备注：,content:支付宝小荷包-10月份攒钱],status:转入成功,amountTip:","regular":"date:(.*?),unit:元,goto:.*?&tradeNO=(\\d+)&bizType=BIZFUND,ad:\\[\\],money:(\\d+\\.\\d{2}),.*?,title:转入成功,actions:\\[.*\\],content:\\[title:付款方式：,content:(.*?),title:对方账户：,content:(.*?),title:转账备注：,content:(.*?)\\],status:转入成功,amountTip:"}],"from":"app"}

**Comment by dreamncn** [comment]
规则请在此提交 http://gitbot.ankio.net/submit/2

**Comment by FroyoRab** [comment]
抱歉，在close issue进行回复，http://gitbot.ankio.net/submit/2 ，404了。
