### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by crow787399294** [dreamncn/Qianji_auto#77]
verCode:涅槃 3.0.0 beta6

error:
Failed to allocate a 2282800 byte allocation with 1154824 free bytes and 1127KB until OOM, target footprint 268435456, growth limit 268435456

stackTrace:
1.java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
2.java.lang.StringBuilder.toString(StringBuilder.java:413)
3.cn.dreamn.qianji_auto.core.helper.Inner.HelpService.onAccessibilityEvent(HelpService.java:107)
4.android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2096)
5.android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2299)
6.com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
7.android.os.Handler.dispatchMessage(Handler.java:106)
8.android.os.Looper.loop(Looper.java:246)
9.android.app.ActivityThread.main(ActivityThread.java:8595)
10.java.lang.reflect.Method.invoke(Native Method)
11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by dreamncn** [comment]
beta10已经修复
