### ISSUE TITLE
提交错误报告

### ISSUE THREAD

**Issue by vhko** [dreamncn/Qianji_auto#79]
verCode:涅槃 3.0.0 beta6

error:
Unable to start activity ComponentInfo{cn.dreamn.qianji_auto/cn.dreamn.qianji_auto.ui.activity.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=6; index=103

stackTrace:
1.android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3711)
2.android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3878)
3.android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
4.android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
5.android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
6.android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
7.android.os.Handler.dispatchMessage(Handler.java:106)
8.android.os.Looper.loop(Looper.java:263)
9.android.app.ActivityThread.main(ActivityThread.java:8253)
10.java.lang.reflect.Method.invoke(Native Method)
11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by dreamncn** [comment]
说明如何复现？
