### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by Halura** [dreamncn/Qianji_auto#80]
verCode:涅槃 3.0.0 beta6

error:
Failed to allocate a 1509688 byte allocation with 1224608 free bytes and 1195KB until OOM, target footprint 268435456, growth limit 268435456

stackTrace:
1.java.lang.StringFactory.newStringFromChars(StringFactory.java:112)
2.java.lang.StringBuilder.toString(StringBuilder.java:413)
3.cn.dreamn.qianji_auto.core.helper.Inner.HelpService.onAccessibilityEvent(HelpService.java:107)
4.android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:2170)
5.android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:2376)
6.com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
7.android.os.Handler.dispatchMessage(Handler.java:106)
8.android.os.Looper.loopOnce(Looper.java:201)
9.android.os.Looper.loop(Looper.java:288)
10.android.app.ActivityThread.main(ActivityThread.java:7842)
11.java.lang.reflect.Method.invoke(Native Method)
12.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
13.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by dreamncn** [comment]
beta10已修复
