### ISSUE TITLE
数据同步后部分一级分类和二级分类缺失

### ISSUE THREAD

**Issue by YagiYui** [dreamncn/Qianji_auto#82]
![Screenshot_2021-11-04-02-24-58-845_cn dreamn qianji_auto](https://user-images.githubusercontent.com/65173370/140170491-a9990699-7453-4de9-9894-bde2a8a77f13.jpg)
![Screenshot_2021-11-04-02-25-12-596_com mutangtech qianji](https://user-images.githubusercontent.com/65173370/140170511-d4631b06-226d-4a98-a62e-0c63d39751c2.jpg)

**Comment by YagiYui** [comment]
![Screenshot_2021-11-04-02-27-12-375_cn dreamn qianji_auto](https://user-images.githubusercontent.com/65173370/140170645-f32c7292-003c-4662-b5ed-b5ccc9a10832.jpg)

**Comment by dreamncn** [comment]
已处理
