### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by YagiYui** [dreamncn/Qianji_auto#83]
verCode:涅槃 3.0.0 beta10

error:
Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

stackTrace:
1.cn.dreamn.qianji_auto.ui.fragment.data.regulars.outFragment.getName(outFragment.java:128)
2.cn.dreamn.qianji_auto.ui.fragment.data.regulars.outFragment.initLayout(outFragment.java:324)
3.cn.dreamn.qianji_auto.ui.fragment.data.regulars.outFragment.initViews(outFragment.java:205)
4.cn.dreamn.qianji_auto.ui.base.BaseFragment.initPage(BaseFragment.java:49)
5.com.xuexiang.xpage.base.XPageFragment.onCreateView(XPageFragment.java:636)
6.androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
7.androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
8.androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
9.androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
10.androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
11.androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
12.androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
13.androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
14.androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
15.androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
16.androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
17.androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
18.androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
19.androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
20.androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
21.androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
22.androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
23.android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
24.android.app.Activity.performStart(Activity.java:8266)
25.android.app.ActivityThread.handleStartActivity(ActivityThread.java:3613)
26.android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
27.android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
28.android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
29.android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
30.android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)
31.android.os.Handler.dispatchMessage(Handler.java:106)
32.android.os.Looper.loop(Looper.java:236)
33.android.app.ActivityThread.main(ActivityThread.java:8168)
34.java.lang.reflect.Method.invoke(Native Method)
35.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
36.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by dreamncn** [comment]
怎么复现？

**Comment by YagiYui** [comment]
没发现规律，有时候打开自动记账就弹

**Comment by dreamncn** [comment]
更新beta15
