### ISSUE TITLE
3.0 B13 添加云端规则后刷新报错

### ISSUE THREAD

**Issue by Zerotimesst** [dreamncn/Qianji_auto#84]
verCode:涅槃 3.0.0 beta13

error:
Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference

stackTrace:
1.cn.dreamn.qianji_auto.utils.files.RegularManager.restoreFromData(RegularManager.java:68)
2.cn.dreamn.qianji_auto.ui.fragment.data.regulars.outFragment$4.handleMessage(outFragment.java:308)
3.android.os.Handler.dispatchMessage(Handler.java:106)
4.android.os.Looper.loop(Looper.java:236)
5.android.app.ActivityThread.main(ActivityThread.java:8168)
6.java.lang.reflect.Method.invoke(Native Method)
7.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
8.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by dreamncn** [comment]
更新beta15
