### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by seametime** [dreamncn/Qianji_auto#86]
verCode:涅槃 3.0.0 beta16

error:
The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131296612, class android.widget.ListView) with Adapter(class cn.dreamn.qianji_auto.ui.adapter.BillListAdapter)]

stackTrace:
1.android.widget.ListView.originalLayoutChildren(ListView.java:1752)
2.android.widget.ListView.layoutChildren(ListView.java:1666)
3.android.widget.AbsListView.onTouchUp(AbsListView.java:4169)
4.android.widget.AbsListView.onTouchEvent(AbsListView.java:3949)
5.android.view.View.dispatchTouchEvent(View.java:13551)
6.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
7.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2767)
8.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
9.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
10.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
11.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
12.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
13.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
14.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
15.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
16.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
17.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
18.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
19.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
20.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
21.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
22.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
23.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
24.android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3088)
25.android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2781)
26.com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:497)
27.com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1853)
28.android.app.Dialog.dispatchTouchEvent(Dialog.java:863)
29.com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:455)
30.android.view.View.dispatchPointerEvent(View.java:13812)
31.android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5649)
32.android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5449)
33.android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4950)
34.android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5003)
35.android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4969)
36.android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5109)
37.android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4977)
38.android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5166)
39.android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4950)
40.android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5003)
41.android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4969)
42.android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4977)
43.android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4950)
44.android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7702)
45.android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7671)
46.android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7632)
47.android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7832)
48.android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:251)
49.android.os.MessageQueue.nativePollOnce(Native Method)
50.android.os.MessageQueue.next(MessageQueue.java:336)
51.android.os.Looper.loop(Looper.java:181)
52.android.app.ActivityThread.main(ActivityThread.java:7560)
53.java.lang.reflect.Method.invoke(Native Method)
54.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
55.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by dreamncn** [comment]
升级
