### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by fargrata** [dreamncn/Qianji_auto#87]
verCode:涅槃 3.0.0 beta6

error:
Failed to allocate a 516608 byte allocation with 435784 free bytes and 425KB until OOM, target footprint 268435456, growth limit 268435456

stackTrace:
1.java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
2.java.lang.StringBuilder.toString(StringBuilder.java:413)
3.cn.dreamn.qianji_auto.core.helper.Inner.HelpService.onAccessibilityEvent(HelpService.java:107)
4.android.accessibilityservice.AccessibilityService$2.onAccessibilityEvent(AccessibilityService.java:1635)
5.android.accessibilityservice.AccessibilityService$IAccessibilityServiceClientWrapper.executeMessage(AccessibilityService.java:1824)
6.com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
7.android.os.Handler.dispatchMessage(Handler.java:107)
8.android.os.Looper.loop(Looper.java:214)
9.android.app.ActivityThread.main(ActivityThread.java:7710)
10.java.lang.reflect.Method.invoke(Native Method)
11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by dreamncn** [comment]
beta7已修复
