### ISSUE TITLE
在支付宝中出现异常

### ISSUE THREAD

**Issue by lormalduss** [dreamncn/Qianji_auto#91]
verCode:涅槃 3.0.0 beta6

error:
Attempt to invoke virtual method 'com.alibaba.fastjson.JSONObject com.alibaba.fastjson.JSONObject.getJSONObject(java.lang.String)' on a null object reference

stackTrace:
1.cn.dreamn.qianji_auto.ui.utils.AutoBillWeb$3.onSuccessful(AutoBillWeb.java:182)
2.cn.dreamn.qianji_auto.ui.utils.AutoBillWeb$1.onResponse(AutoBillWeb.java:72)
3.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
4.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
5.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
6.java.lang.Thread.run(Thread.java:919)

**Comment by lormalduss** [comment]
实际自动记账仍可正常执行，
只是无法进入模块主界面。

**Comment by dreamncn** [comment]
云规则问题，已云修复。
