### ISSUE TITLE
后台运行跳出报告异常

### ISSUE THREAD

**Issue by led-ury** [dreamncn/Qianji_auto#92]
verCode:涅槃 3.0.0 beta6

error:
Failed to allocate a 359464 byte allocation with 335072 free bytes and 327KB until OOM, target footprint 268435456, growth limit 268435456

stackTrace:
1.android.database.CursorWindow.nativeGetString(Native Method)
2.android.database.CursorWindow.getString(CursorWindow.java:469)
3.android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
4.cn.dreamn.qianji_auto.database.Dao.LogDao_Impl.loadAll(LogDao_Impl.java:171)
5.cn.dreamn.qianji_auto.utils.runUtils.Log.lambda$getAll$5(Log.java:115)
6.cn.dreamn.qianji_auto.utils.runUtils.-$$Lambda$Log$VfG2CmrEeUdcYxm2W6pybRzd-VU.run(Unknown Source:2)
7.cn.dreamn.qianji_auto.utils.runUtils.Task.onThread(Task.java:60)
8.cn.dreamn.qianji_auto.utils.runUtils.Log.getAll(Log.java:113)
9.cn.dreamn.qianji_auto.ui.fragment.data.LogFragment.lambda$loadFromData$4$LogFragment(LogFragment.java:192)
10.cn.dreamn.qianji_auto.ui.fragment.data.-$$Lambda$LogFragment$U3jZytV6aDFAAuaN9_nV8fpJ6XI.run(Unknown Source:2)
11.java.lang.Thread.run(Thread.java:919)

**Comment by dreamncn** [comment]
已在 beta7 修复
