### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Lon-dawn** [dreamncn/Qianji_auto#96]
verCode:涅槃 3.0.0 beta6

error:
Animators may only be run on Looper threads

stackTrace:
1.android.animation.ValueAnimator.cancel(ValueAnimator.java:1112)
2.cn.dreamn.qianji_auto.ui.components.Loading.LVCircularRing.stopAnim(LVCircularRing.java:79)
3.cn.dreamn.qianji_auto.ui.components.Loading.LoadingDialog.close(LoadingDialog.java:44)
4.cn.dreamn.qianji_auto.ui.fragment.data.regulars.remoteFragment$2$2.onFailure(remoteFragment.java:254)
5.cn.dreamn.qianji_auto.ui.utils.AutoBillWeb$1.onResponse(AutoBillWeb.java:74)
6.okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
7.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
8.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
9.java.lang.Thread.run(Thread.java:923)

**Comment by songyongguo1987** [comment]
verCode:涅槃 3.0.0 beta26

error:
Unable to start activity ComponentInfo{cn.dreamn.qianji_auto/cn.dreamn.qianji_auto.ui.activity.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=6; index=99

stackTrace:
1.android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3526)
2.android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3665)
3.android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
4.android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151)
5.android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111)
6.android.app.ActivityThread$H.handleMessage(ActivityThread.java:2228)
7.android.os.Handler.dispatchMessage(Handler.java:107)
8.android.os.Looper.loop(Looper.java:238)
9.android.app.ActivityThread.main(ActivityThread.java:7905)
10.java.lang.reflect.Method.invoke(Native Method)
11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

**Comment by dreamncn** [comment]
> verCode:涅槃 3.0.0 beta26
> 
> error: Unable to start activity ComponentInfo{cn.dreamn.qianji_auto/cn.dreamn.qianji_auto.ui.activity.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=6; index=99
> 
> stackTrace: 1.android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3526) 2.android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3665) 3.android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 4.android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151) 5.android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111) 6.android.app.ActivityThread$H.handleMessage(ActivityThread.java:2228) 7.android.os.Handler.dispatchMessage(Handler.java:107) 8.android.os.Looper.loop(Looper.java:238) 9.android.app.ActivityThread.main(ActivityThread.java:7905) 10.java.lang.reflect.Method.invoke(Native Method) 11.com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 12.com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

请确定已经安装钱迹
