### ISSUE TITLE
App识别：『南北』微信公众号_中国银行_支出

### ISSUE THREAD

**Issue by Oniokey** [dreamncn/Qianji_auto#99]
{"data":[{"des":"","identify":"app","fromApp":"com.tencent.mm","name":"『南北』微信公众号_中国银行_支出","tableList":{"shopRemark":"$7","money":"$5","fee":"","account2":"","account1":"储蓄卡（$2）","shopName":"$6","time":"$1","type":"0"},"text":"cache_user:微信红包,cache_user2:中国银行微银行,cache_paytools:中国银行储蓄卡(2218),isSend:0,title:卡片消息,content:msg:appmsg:extinfo:,lowurl:,sourcedisplayname:,showtype:1,title:交易提醒,type:5,appattach:totallen:0,cdnthumburl:,aeskey:,attachid:,fileext:,cdnthumbaeskey:,content:ntt,content:,url:https://mbas.mbs.boc.cn/WeiBankFront/weixinVue/itemClick/index.html#/itemClick?appid=wx567af860fd4db040&factorId=01fe2f9195014f60a21836ccfa1e5db9&temId=WSAP0001&adId=176&url=https%3A%2F%2Fmbs.boc.cn%2Fv%2Fa%2Fp3Asdqq747,soundtype:0,mmreader:template_detail:,publisher:nickname:中国银行微银行,content:nttt,username:bocebanking,template_header:,category:item:is_pay_subscribe:0,video_height:0,sources:source:name:中国银行微银行,content:ntttttt,content:nttttt,appmsg_like_type:0,video_width:0,recommendation:,title:交易提醒,native_url:,content:ntttt,cover:,weapp_version:0,vid:,pic_num:0,digest:尊敬的王天成，您尾号为2218的储蓄账户nnn交易时间：12月19日00:06n交易类型：网上快捷支付n交易金额：人民币 0.50n账户余额：3.69元n对方账户：财付通-微信红包n交易渠道：银企对接n交易备注：财付通-微信红包nn话费充值享优惠，随机立减5-20元，快来点击参与！,cover_235_1:,weapp_username:,fileid:0,player:,cover_1_1:,del_flag:0,play_url:,shorturl:,pub_time:1639843589,pic_urls:,cover_16_9:,general_string:,template_op_type:0,weapp_path:,url:https://mbas.mbs.boc.cn/WeiBankFront/weixinVue/itemClick/index.html#/itemClick?appid=wx567af860fd4db040&factorId=01fe2f9195014f60a21836ccfa1e5db9&temId=WSAP0001&adId=176&url=https%3A%2F%2Fmbs.boc.cn%2Fv%2Fa%2Fp3Asdqq747,tweetid:,finder_feed:,play_length:0,comment_topic_id:0,music_source:0,longurl:,styles:topColor:#E25050,style:[color:#000000,range:0,20,content:ntttttt,font:s,color:#000000,range:28,11,content:ntttttt,font:s,color:#000000,range:45,6,content:ntttttt,font:s,color:#3333FF,range:57,8,content:ntttttt,font:s,color:#222222,range:66,75,content:ntttttt,font:s],content:nttttt,itemshowtype:4,contentattr:0,weapp_state:0,show_complaint_button:1,count:1,name:中国银行微银行,topnew:cover:,width:0,digest:尊敬的王天成，您尾号为2218的储蓄账户nnn交易时间：12月19日00:06n交易类型：网上快捷支付n交易金额：人民币 0.50n账户余额：3.69元n对方账户：财付通-微信红包n交易渠道：银企对接n交易备注：财付通-微信红包nn话费充值享优惠，随机立减5-20元，快来点击参与！,content:ntttt,height:0,type:0,content:nttt,content:ntt,forbid_forward:0,notify_msg:,des:尊敬的王天成，您尾号为2218的储蓄账户nnn交易时间：12月19日00:06n交易类型：网上快捷支付n交易金额：人民币 0.50n账户余额：3.69元n对方账户：财付通-微信红包n交易渠道：银企对接n交易备注：财付通-微信红包nn话费充值享优惠，随机立减5-20元，快来点击参与！,appid:,sourceusername:,sdkver:0,action:,template_id:nHc3DBFf2VewzkunmgKxVSnNRCz3DSM2wNCZun44mLI,thumburl:,contentattr:0,fromusername:gh_19b52c2473d6,appinfo:appname:中国银行微银行,version:0,content:nt,isforceupdate:1,content:nt,status:3,cache_money:￥0.50","regular":"pub_time:(.*),pic_urls.*,notify_msg:,des:尊敬的.*，您尾号为(.*)的储蓄账户nnn交易时间：(.*)n交易类型：(.*)n交易金额：.* (.*)n账户余额：\\d+\\.\\d+?元n对方账户：(.*)n交易渠道：(.*)n交易备注：.*nn"}],"from":"app"}

**Comment by dreamncn** [comment]
规则提交到此处：https://github.com/dreamncn/AutoResource
